### PR TITLE
Fixed problem that prevented global flow from working

### PR DESCRIPTION
**Pull request by c0r73x**
The problem seems to be that if the path `./node_modules/flow-bin` is missing then `os.listdir` fails. Without this fix globally installed flow wont work (atleast not on my setup).

### CODE REVIEW

**Comment by roxma** [comment]
This PR breaks local flow detection.

> Without this fix globally installed flow wont work (atleast not on my setup).

Could you post your log files? It's working on my setup.

**Comment by c0r73x** [comment]
Hi, here is the log from the master branch https://vvt.nu/a4x and here is the log with this PR  https://vvt.nu/WGw when flow is located at /usr/bin/flow without the folder node_modules/bin-flow.

Here is the folder structure that I tested with.
```
├── .flowconfig
└── test.js
```
And the test file.
```javascript
/* @flow */

const obj = {
    string: 'test',
    number: 1,
};

obj.
```

**Comment by roxma** [comment]
There's no content in the page you send, is it expired?

**Comment by c0r73x** [comment]
Yeah, sorry. I've pasted it on a gist instead. https://gist.github.com/c0r73x/a1173d22438039e6877e68a335588b1b

**Comment by roxma** [comment]
That's the log of ncm core.

You should look for the log file with 'flow' in the name.

**Comment by c0r73x** [comment]
I dont get a file like that when running `NVIM_PYTHON_LOG_FILE=nvim.log NVIM_PYTHON_LOG_LEVEL=INFO nvim` do i need to enable something in ncm?

```
.
├── .flowconfig
├── nvim.log_py2_script
├── nvim.log_py3_cm_core
├── nvim.log_py3_rplugin
├── nvim.log_py3_script
└── test.js
```

**Comment by roxma** [comment]
Also disable threading, it's easier for debugging:

`NVIM_PYTHON_LOG_FILE=nvim.log NVIM_NCM_LOG_LEVEL=DEBUG NVIM_NCM_MULTI_THREAD=0 nvim`

**Comment by c0r73x** [comment]
Ok now I got it https://gist.github.com/c0r73x/3d5006e1a38aab819a736a645d5e698e

I tested to add local flow-bin and yeah something is wrong with the PR beacuse it fallbacks. I will fix it for both local and global flow.

**Comment by c0r73x** [comment]
Now it works for both global and local flow, not sure why you did use the paths from node_modules/flow-bin/ instead of node_modules/.bin/flow though.

**Comment by roxma** [comment]
Thanks

**Pull request merged**
